
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root 
#    password: srivatsan
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: tour-service
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true       
#  profiles:
#  - dev
#
#server:
#  port: 5858
#
#eureka:
#  client:
#    service-url:
#      defaultZone:  http://localhost:8761/eureka
#
#logging:
#  level:
#    '[org.springframework.web]': trace
#    '[org.springframework.data.jpa.repository]': trace
#    '[org.hibernate]': trace
#    
#    
#---
# 
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root 
#    password: srivatsan
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: tour-service
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true       
#  profiles:
#  - prod
#
#server:
#  port: 5454
#
#eureka:
#  client:
#    service-url:
#      defaultZone:  http://localhost:8761/eureka
#
#logging:
#  level:
#    '[org.springframework.web]': trace
#    '[org.springframework.data.jpa.repository]': trace
#    '[org.hibernate]': trace   
#    
    
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root 
#    password: srivatsan
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: tour-service
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true       
#  
#
#server:
#  port: ${port:0}
#
#eureka:
#  client:
#    service-url:
#      defaultZone:  http://localhost:8761/eureka
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    
#    
#    
#  
#     


  